export enum AppState {
    CONNECTING = "CONNECTING",
    AUTH = "AUTH",
    RECOVERING = "RECOVERING",
    MATCHING = "MATCHING",
    WAITING_FOUND = "WAITING_FOUND",
    WAITING_BEGIN = "WAITING_BEGIN",
    PLAYING = "PLAYING",
    GAME_OVER = "GAME_OVER",
    ERROR = "ERROR"
}
